#!/usr/bin/env node
/**
 * Creates cms/strapi/.env with local development secrets.
 * Existing files are left untouched unless --force is passed.
 */
import { randomBytes } from "node:crypto";
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const envPath = path.join(repoRoot, "cms", "strapi", ".env");
const force = process.argv.includes("--force");

function secret(bytes = 32) {
  return randomBytes(bytes).toString("base64url");
}

if (existsSync(envPath) && !force) {
  console.log("cms/strapi/.env already exists. Use `npm run cms:env -- --force` to regenerate it.");
  process.exit(0);
}

mkdirSync(path.dirname(envPath), { recursive: true });
writeFileSync(
  envPath,
  `# Generated by npm run cms:env. Keep this file local.
HOST=0.0.0.0
PORT=1337
APP_KEYS=${[secret(), secret(), secret(), secret()].join(",")}
API_TOKEN_SALT=${secret()}
ADMIN_JWT_SECRET=${secret()}
TRANSFER_TOKEN_SALT=${secret()}
JWT_SECRET=${secret()}

# Local npm run cms:dev uses SQLite.
DATABASE_CLIENT=sqlite
DATABASE_FILENAME=.tmp/data.db

# Docker Compose profile overrides these for Postgres.
# DATABASE_CLIENT=postgres
# DATABASE_HOST=postgres
# DATABASE_PORT=5432
# DATABASE_NAME=gogocash_cms
# DATABASE_USERNAME=gogocash
# DATABASE_PASSWORD=gogocash_dev_password
# DATABASE_SSL=false
`,
  "utf8",
);

console.log("Created cms/strapi/.env");
